config/routes.rb
App::Application.routes.draw do

  get "stores/new"
  get "store/new"

  #test pages
  get "test/setup"
  get "test/simple_search_test_input"
  post "test/test_simple_search"

  #match '/', :to => "sessions#new"
  match '/', :to => "login#show"
  match "/stores/:id", :to => "stores#show", :as => :show_store
  match "/add_review", :to => "stores#addreview"

  post "/users", :to => "users#create"
  post "/lists", :to => "lists#create"
  post "/sessions", :to => "sessions#create"
  post "/stores", :to => "stores#create"

  match "/search/advanced", :to => "simple_search#search_advanced", :as => :search_advanced
  match "/search/get_list", :to => "simple_search#get_list"
  match "/search/approve_tag", :to => "simple_search#approve_tag"

  match "/users/:id/:cur_list", :to => "users#show", :as => :default_home
  match "/users/:id", :to => "users#show", :as => :home
  match "/signup",  :to => "users#new"
  match "/signin", :to => "sessions#new"
  match "/signout", :to => "sessions#destroy"
  match "/createlist", :to => "lists#new"
  match "/sublist", :to => "lists#subscribe_list"
  match "/deletelist/:id", :to => "lists#destroy", :as => :delete_list
  match "/unsublist/:list_id", :to => "lists#unsubscribe_list", :as => :unsub_list

  match "/addtolist/:list_id/:store_id", :to => "lists#add", :as => :add_to_list
  match "/removefromlist/:list_id/:store_id", :to => "list_stores#destroy", :as => :remove_from_list

  match "/addstore", :to => "stores#new"
  match "/search/", :to => "simple_search#search"

  match "/login", :to => "login#show"
  match "/homepage/:access_token", :to => "login#login"
  match "/showcurrlists", :to => "lists#show_curr_lists", :as => :show_curr_lists
  match "/showpossiblelists", :to => "lists#show_possible_lists", :as => :show_possible_lists
  match "/showcurrlisters", :to => "lists#show_curr_listers", :as => :show_curr_listers
   
  match "/view-tags", :to => "stores#view_tags"
  match "/add-tags", :to => "stores#add_tags"
  
  # this line giving error while running the server
  #resources :sessions, :only [:new, :create, :destroy]

  #resources :users

  # match '/signup', :to => 'users#new'

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :list_users, :dependent => :destroy
	has_many :users, :through => :lists_users
	has_many :list_stores, :dependent => :destroy
	has_many :stores, :through => :lists_stores
	attr_accessible :deletable, :name

end

app/controllers/list_controller.rb
class ListController < ApplicationController

	def new
		@list = List.new

		respond_to do |format|
  		format.html #new.html.erb
  		format.json { render :json => @list}
	end

	def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, :notice => 'List was successfully created.' }
        format.json { render :json => @list, :status => :created, :location => @list }
      else
        format.html { render :action => "new" }
        format.json { render :json => @list.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to :js

	def new
		list = ListLogic.create_new_list(nil)
    friends = FriendLogic.find_friends(session[:user_id])
    user = User.find_by_id(session[:user_id])
	  render :partial => "lists/new", :locals => {:friends => friends, :list => list, :user => user}
	end

	def create
      @list = ListLogic.create_new_list(params[:list])
      @list.deletable = true
      respond_to do |format|
        if @list.save
          # get curent user
          user_id = session[:user_id]
          user_entity = UserEntity.new
          user_entity.find_by_id(user_id)
          user_entity.add_new_list(@list, 0)

          #set up permissions for friends of creating user
          params.each do |parameter|
            if parameter[0].starts_with? 'friend'
                user_entity.find_by_id(parameter[0].split('.')[1])
                user_entity.add_new_list(@list, 1)
            end
          end

          format.html { redirect_to default_home_path(session[:user_id], @list.id), :notice => 'List was successfully created.' }
          format.json { render :json => @list, :status => :created, :location => @list }
        else
          #format.html { render :action => "new" }
          format.json { render :json => @list.errors, :status => :unprocessable_entity }
        end
      end
  	end

    def add
        #@list = List.find(params[:list_id])
        list_id = params[:list_id]
        store_id = params[:store_id]
        list_entity = ListEntity.new(list_id)
        
        respond_to do |format|
          @list_store = list_entity.add_store_to_current_list(store_id)
          puts list_id
          puts store_id
          puts "#*********#"
          puts @list_store.store.name
          
          format.html { redirect_to default_home_path(session[:user_id], list_id), :notice => 'List successfully edited'}
          format.json { render :json => @list, :status => :edited, :location => @list}
        end
    end

    def destroy
      list_id = params[:id]

      if ListLogic.check_deletable(list_id)
        user_id = session[:user_id]
        user_entity = UserEntity.new
        user_entity.find_by_id(user_id)
        user_entity.delete_user_list(list_id)

      end
      
      # after delete, you need to reload the list so create
      # the new user which reload the list by default.
      user_entity2 = UserEntity.new
      user_entity2.find_by_id(user_id)
      default_list_id = user_entity2.find_user_default_list
      #default_list_id = ListUser.find_default_list(session[:user_id])

      respond_to do |format|
        if default_list_id
          format.html { redirect_to default_home_path(session[:user_id], default_list_id) }
          format.json { head :no_content }
        else
          format.html { redirect_to home_path(session[:user_id]) }
          format.json { head :no_content }
        end
      end
    end

  #display lists on store drop down menu
  def show_possible_lists
      @curr_lists = ListFinder.find_lists_by_curr_store(params[:store_id], session[:user_id])

      if(@curr_lists.empty?)
          @not_on_lists = ListFinder.find_users_lists(session[:user_id])
      else
          list_names = Array.new
          @curr_lists.each do |list|
            list_names.push(list.name)
          end
          @not_on_lists = ListFinder.find_all_other_lists(list_names, session[:user_id])
      end

      @store_id = params[:store_id]
    render :partial => "lists/show_possible_lists", :locals => {:store_id => @store_id}
  end

  def show_curr_lists

      @curr_lists = ListFinder.find_lists_by_curr_store(params[:store_id], session[:user_id])
      @store_id = params[:store_id]

    render :partial => "lists/show_curr_lists", :locals=>{:curr_lists => @curr_lists, :store_id =>@store_id}
  end

  #return list of lists that this store belongs to, and owner of those lists
  def show_curr_listers
    print  "params[:lists] \n"
    print params[:lists]
    print "\n"
    print "storeid : \n"
    print params[:store_id]
    print "\n"
    @curr_lists = ListFinder.find_listers(params[:lists], params[:store_id])
    render :partial => "lists/show_curr_listers", :locals => { :curr_lists => @curr_lists, :store_id => params[:store_id]}
    
  end

  def subscribe_list
    ListLogic.subscribe_list(session[:user_id], params[:list_id])
    #redirect to homepage? idk...
  end

  def unsubscribe_list
    ListLogic.unsubscribe_list(session[:user_id], params[:list_id])

   redirect_to home_path(session[:user_id])
  end

end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list, :url => { :action => :create } do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_list_display.html.erb
<ul class='nav nav-list'>
	<li class='nav-header'>
		<h3> <% if user.id != current_user_id %>
		<% friends.each do |friend| %>
		<% if friend.id == user.id %>
		<%= friend.first_name %>'s Lists
		<% end %>
		<% end %>
		<% else %>
		My Lists
		<% end %> <span>
			<button class='btn' id='create_list' style='float:right; margin-top:0;'>
				Add
			</button></span></h3>
	</li>
	<% users_lists.each do |list| %>
	   <li class="divider"></li>
    	<% if list.id != current_list.id %>
    	   <li>
        <% else %>
    	   <li class='active'>
    	<% end%>
		<a href='<%= default_home_path(user.id, list.id)%>'> <% if list.name == "Places I've Been To"%> <i class="icon-flag"></i> <% elsif list.name =="Places I Want To Go"%> <i class="icon-bookmark"></i> <% elsif list.name =="Favorites"%> <i class="icon-star"></i> <% else %> <i class="icon-list-alt"></i> <% end %>
		<%= list.name %></a>
		<% if user.id == current_user_id%>
    		<% if list.deletable == true %>
    		<a href='<%= delete_list_path(list.id) %>' style="float:right;"><i class="icon-remove-sign" 	style='float:right; margin-top:-22px;' alt="remove list"></i></a>
    		<% else %>
    		<i class="icon-lock" style='float:right;'></i>
    		<% end %>
		<% else %>
    		<% unless curr_user_subs.include? list.id %>
    		  <i class='subscribe_list list.<%= list.id%> icon-share' style='float:right;'></i>
            <% end %>
	    <% end %>
	   </li>
	<% end %>
	
	<li class='divider'></li>
	<li class='nav-header' >
		<h3>Group Lists</h3>
	</li>
	<% group_lists.each do |list| %>
    	<% if list.id != current_list.id %>
    	   <li>
        <% else %>
    	   <li class='active'>
        <% end %>
    		<a href='<%= default_home_path(user.id, list.id)%>'> <i class="icon-list-alt"></i> <%= list.name %></a>
        		<% if user.id == current_user_id %>
        		  <% if list.deletable == true %>
        		      <a href='<%= delete_list_path(list.id) %>' style="float:right;"><i class="icon-remove-sign" 	style='float:right; margin-top:-22px;' alt="remove list"></i></a>
        		  <% else %>
        		      <i class="icon-lock" style='float:right;'></i>
        		  <% end %>
    		    <% end %>
    	   </li>
	<% end %>

	<li class='divider'></li>
	<li class='nav-header'>
		<h3>Subscribed Lists</h3>
		<% subbed_lists.each do |list| %>
		<% if list.id != current_list.id %>
	<li>
		<% else %>
	<li class='active'>
		<% end %>
		<a href='<%= default_home_path(user.id, list.id)%>'> <i class="icon-list-alt"></i> <%= list.name + " (" + sub_owners[list.id].to_s + ")" %></a>
		<% if user.id == current_user_id %>
		<a href='<%= unsub_list_path(list.id) %>' style="float:right;"><i class="icon-remove-sign" 	style='float:right; margin-top:-22px;' alt="remove list"></i></a>
		<% else %>
		<% unless curr_user_subs.include? list.id %>
		<span>
			<button class='subscribe_list list.<%= list.id%>' style='float:right; margin-top:0;'>
				Sub
			</button></span>
		<% end %>
		<% end %>
	</li>
	<% end %>
	</li>
</ul>

<div id="modal_div_create_lists"></div>

app/views/lists/_new.html.erb
<div class="modal hide" id="modal_create_list">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">
			×
		</button>
		<h3>Create New List</h3>
	</div>
	<%= form_for list, :url => { :action => :create } do |f| %>

	<div class="modal-body">
		<div class="field">
			<%= f.label :name%>
			<%= f.text_field :name, :placeholder=>"Required"  %>
		</div>

		<div class="control-group">
		    <label class="control-label">Allow Permission to Edit</label>
		    <div class="controls">
                <label class='checkbox'><input type="checkbox" checked='checked' disabled="disabled"><span><%= user.first_name+' '+user.last_name %> (me) </span><i class='icon-lock'></i></label>
			<% friends.each do |friend| %>
			    <label class='checkbox'> <%= check_box_tag 'friend.'+friend.id.to_s %><span><%= friend.first_name+' '+friend.last_name %></span></label>
			<% end %>
			</div>
		</div>
	</div>

	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
		<button type='submit' name='commit' class="btn btn-primary">
			Save changes
		</button>
	</div>
	<% end %>
</div>

app/views/lists/_show_curr_listers.html.erb
<div class="modal hide" id="show_curr_listers_modal-<%=store_id%>">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">
			×
		</button>
		<h3>Listers</h3>
	</div>
	<div class="modal-body">
		<form>
			<ul class="nav nav-list">
				<% curr_lists.each do |list| %>
				<li>
					<%= list[0] %>(<%= list[1] %>)
				</li>
				<li class="divider"></li>
				<% end %>
			</ul>
		</form>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
</div>

app/views/lists/_show_curr_lists.html.erb
<div class="modal hide" id="show_curr_list_modal-<%=store_id%>">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">
			×
		</button>
		<h3>Select List</h3>
	</div>
	<div class="modal-body">
		<form>
			<ul class="nav nav-list">
				<% curr_lists.each do |list| %>
				<li>
					<%= link_to list.name, remove_from_list_path(list.id, store_id) %>
				</li>
				<li class="divider"></li>
				<% end %>
			</ul>
		</form>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
</div>



app/views/lists/_show_possible_lists.html.erb
<div class="modal hide" id="modal-<%=store_id%>">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">
			×
		</button>
		<h3>Select List</h3>
	</div>
	<div class="modal-body">
	    <form>
		<ul class="nav nav-list">
			<% @not_on_lists.each do |list| %>
			<li>
				<%= link_to list.name, add_to_list_path(list.id, store_id) %>
			</li>
			<li class="divider"></li>
			<% end %>
		</ul>
		</form>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
</div>

app/views/lists/display_lists.js.erb
var test = $('TESTING123');
$('#test_div').html("CURRENTLY ON: <br><% @curr_list_names.each do |list| %> <%= list %><br> <% end %><br> NOT ON: <br><% @not_on_lists.each do |list| %> <%= list %><br> <% end%>");